
// This file has been generated by the GUI designer. Do not modify.
namespace ConnectionMap
{
	public partial class SaveMapMenu
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview2;
		
		private global::Gtk.ToggleButton togglebutton1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ConnectionMap.SaveMapMenu
			this.Name = "ConnectionMap.SaveMapMenu";
			this.Title = global::Mono.Unix.Catalog.GetString ("SaveMapMenu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.DefaultWidth = 100;
			this.DefaultHeight = 10;
			// Container child ConnectionMap.SaveMapMenu.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Map Name");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.WidthRequest = 75;
			this.textview2.HeightRequest = 10;
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.textview2.AcceptsTab = false;
			this.GtkScrolledWindow.Add (this.textview2);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.togglebutton1 = new global::Gtk.ToggleButton ();
			this.togglebutton1.CanFocus = true;
			this.togglebutton1.Name = "togglebutton1";
			this.togglebutton1.UseUnderline = true;
			this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.vbox1.Add (this.togglebutton1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.togglebutton1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.togglebutton1.Clicked += new global::System.EventHandler (this.on_save);
		}
	}
}
