
// This file has been generated by the GUI designer. Do not modify.
namespace ConnectionMap
{
	public partial class MainControl
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action OptionsAction;
		
		private global::Gtk.Action ThemesAction;
		
		private global::Gtk.Action DefaultAction;
		
		private global::Gtk.Action DesertAction;
		
		private global::Gtk.Action ForestAction;
		
		private global::Gtk.Action DarkAction;
		
		private global::Gtk.Action MidnightAction;
		
		private global::Gtk.Action CorduroyAction;
		
		private global::Gtk.Action LunarAction;
		
		private global::Gtk.Action CustomThemesAction;
		
		private global::Gtk.Action CreateNewThemeAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar menubar2;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TextView console_tv;
		
		private global::Gtk.Button refresh_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ConnectionMap.MainControl
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.OptionsAction = new global::Gtk.Action ("OptionsAction", global::Mono.Unix.Catalog.GetString ("Options"), null, null);
			this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Options");
			w1.Add (this.OptionsAction, null);
			this.ThemesAction = new global::Gtk.Action ("ThemesAction", global::Mono.Unix.Catalog.GetString ("Themes"), null, null);
			this.ThemesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Themes");
			w1.Add (this.ThemesAction, null);
			this.DefaultAction = new global::Gtk.Action ("DefaultAction", global::Mono.Unix.Catalog.GetString ("Default"), null, null);
			this.DefaultAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Default");
			w1.Add (this.DefaultAction, null);
			this.DesertAction = new global::Gtk.Action ("DesertAction", global::Mono.Unix.Catalog.GetString ("Desert"), null, null);
			this.DesertAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Desert");
			w1.Add (this.DesertAction, null);
			this.ForestAction = new global::Gtk.Action ("ForestAction", global::Mono.Unix.Catalog.GetString ("Forest"), null, null);
			this.ForestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Forest");
			w1.Add (this.ForestAction, null);
			this.DarkAction = new global::Gtk.Action ("DarkAction", global::Mono.Unix.Catalog.GetString ("Dark"), null, null);
			this.DarkAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dark");
			w1.Add (this.DarkAction, null);
			this.MidnightAction = new global::Gtk.Action ("MidnightAction", global::Mono.Unix.Catalog.GetString ("Midnight"), null, null);
			this.MidnightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Midnight");
			w1.Add (this.MidnightAction, null);
			this.CorduroyAction = new global::Gtk.Action ("CorduroyAction", global::Mono.Unix.Catalog.GetString ("Corduroy"), null, null);
			this.CorduroyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Corduroy");
			w1.Add (this.CorduroyAction, null);
			this.LunarAction = new global::Gtk.Action ("LunarAction", global::Mono.Unix.Catalog.GetString ("Lunar"), null, null);
			this.LunarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Lunar");
			w1.Add (this.LunarAction, null);
			this.CustomThemesAction = new global::Gtk.Action ("CustomThemesAction", global::Mono.Unix.Catalog.GetString ("Custom Themes"), null, null);
			this.CustomThemesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Custom");
			w1.Add (this.CustomThemesAction, null);
			this.CreateNewThemeAction = new global::Gtk.Action ("CreateNewThemeAction", global::Mono.Unix.Catalog.GetString ("Create New Theme"), null, null);
			this.CreateNewThemeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create New Theme");
			w1.Add (this.CreateNewThemeAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "ConnectionMap.MainControl";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainControl");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ConnectionMap.MainControl.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ThemesAction' action='ThemesAction'><menuitem name='DefaultAction' action='DefaultAction'/><menuitem name='DesertAction' action='DesertAction'/><menuitem name='ForestAction' action='ForestAction'/><menuitem name='DarkAction' action='DarkAction'/><menuitem name='MidnightAction' action='MidnightAction'/><menuitem name='CorduroyAction' action='CorduroyAction'/><menuitem name='LunarAction' action='LunarAction'/><menu name='CustomThemesAction' action='CustomThemesAction'><menuitem name='CreateNewThemeAction' action='CreateNewThemeAction'/></menu></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox2.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.console_tv = new global::Gtk.TextView ();
			this.console_tv.HeightRequest = 250;
			this.console_tv.CanFocus = true;
			this.console_tv.Name = "console_tv";
			this.scrolledwindow1.Add (this.console_tv);
			this.hbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.scrolledwindow1]));
			w5.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.refresh_button = new global::Gtk.Button ();
			this.refresh_button.CanFocus = true;
			this.refresh_button.Name = "refresh_button";
			this.refresh_button.UseUnderline = true;
			this.refresh_button.Label = global::Mono.Unix.Catalog.GetString ("Refresh Map");
			this.hbox2.Add (this.refresh_button);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.refresh_button]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 553;
			this.Show ();
			this.DefaultAction.Activated += new global::System.EventHandler (this.set_default_theme);
			this.DesertAction.Activated += new global::System.EventHandler (this.set_desert_theme);
			this.ForestAction.Activated += new global::System.EventHandler (this.set_forest_theme);
			this.DarkAction.Activated += new global::System.EventHandler (this.set_dark_theme);
			this.MidnightAction.Activated += new global::System.EventHandler (this.set_midnight_theme);
			this.CorduroyAction.Activated += new global::System.EventHandler (this.set_corduroy_theme);
			this.LunarAction.Activated += new global::System.EventHandler (this.set_lunar_theme);
			this.CreateNewThemeAction.Activated += new global::System.EventHandler (this.set_custom_theme);
			this.refresh_button.Clicked += new global::System.EventHandler (this.onRefresh);
		}
	}
}
