
// This file has been generated by the GUI designer. Do not modify.
namespace ConnectionMap
{
	public partial class CustomMapWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ConnectionMap.CustomMapWindow
			this.Name = "ConnectionMap.CustomMapWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("CustomMapWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
